### ISSUE TITLE
Dir structure during build

### ISSUE THREAD

**Issue by knausb** [grunwaldlab/quiltr#39]
If I want to query the contents of the data directory from the project root I would use:

```
ls data/
```

If I put this in my note, it fails.  I instead need to use:

ls _data/

This seems non-intuitive to me.  Should this be handled differently?  If you need to copy the project before building you could create a .tmp dir in the project root.  But I'm not sure that's the issue.

**Comment by zachary-foster** [comment]
When the Rmd's are knitted, the current working directory is changed to the Rmd's working directory, so the `data` directory of the notebook would actually be `../../data`. The `_data` in each note is a link to `../../data`. I could name the link `data` instead of `_data`, but I was concerned that doing so might give the wrong impression that the current working directory during building the website is the notebook root, rather than the note directories. 

Do you think it would be better to name the links without the leading underscore?

**Comment by zachary-foster** [comment]
This is no longer applicable after abstracting the website build function.
