### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by grunwald** [grunwaldlab/quiltr#52]
Please add examples of a notebook init as well as edits and requilting to both the markdown site and the 

> ?quilt()

help command. I could not get started as presented.

I believe there should be basic example folder so that folks can work right away with the skeleton of a notebook. 

Show one example where you write an R markdown file that is knitted to html and rendered using quilt() into a notebook.

**Comment by zachary-foster** [comment]
I am working on adding templates which will address some of these issues. 
Template functions will provide a way to generate directories ready to be quilted with certain predefined options.
These will also be examples since they will have some dummy content. 
Once I have one of the templates working, I will add a "templates" section to the documentation and a "quick start" guide that uses a template. 
The same examples in the quick start guide should be short enough to add to the ?quilt function/documentation. 

Its hard to effectively demonstrate creating and knitting Rmd files in vignettes without providing a bunch of screen shots of RStudio, which will make the package source big. 
What do you think of a YouTube video tutorial that can be displayed on the website?

**Comment by grunwald** [comment]
Video tutorials are a lot of work and get outdated easily. I would use  Rmakrdown wherever possible so that things are up-to-date.
